name: MyAuth
main: MyAuth\MyAuth
version: "1.0-dev#5"
api: [3.0.0-ALPHA3]
load: STARTUP
author: SuperPuperSteve
description: Authentication plugin

commands:
 register:
  aliases: ['reg']
  description: Register an account
 login:
  aliases: ['l']
  description: Login into an account
 unregister:
  description: Unregister an account
 changepassword:
  aliases: ['passwd', 'chp']
  description: Changes password
 logout:
  description: Log out from an account
 myadmin:
  description: MyAuth admin

permissions:
 myauth:
  description: MyAdmin global permission
  default: op
  
  children:
   myauth.myadmin:
    description: MyAdmin admin
    default: op
