name: MyAuth
main: MyAuth\MyAuth
version: "0.3"
api: [3.0.0-ALPHA3]
load: STARTUP

commands:
 register:
  aliases: ['reg']
  description: Register an account
 login:
  aliases: ['l']
  description: Login into an account
 unregister:
  description: Unregister an account
 changepassword:
  aliases: ['passwd', 'chp']
  description: Changes password
