---
#IP, по которому идёт подключение к MySQL
ip: '127.0.0.1'
#Имя пользователя MySQL
username: 'auth'
#Пароль пользователя MySQL
password: '12345'
#Имя базы данных, в которой будет хранится информация о паролях
database: 'authdb'
#Префикс таблиц (не обязательно)
table_prefix: ''
...