---
# Database type (mysql)
# Тип базы данных
type: mysql

# Database IP
# IP базы данных 
# (mysql)
ip: '127.0.0.1'
# Database username 
# Имя пользователя 
# (mysql)
username: 'auth'
# Username's password
# Пароль пользователя
# (mysql)
password: '12345'
# Database/Folder name
# Имя базы данных/папок
# (mysql, yaml)
database: 'authdb'
# Database tables/folder prefix
# Префикс таблиц базы данных/папок
# (mysql, yaml)
table_prefix: ''

# Plugin language (ru/en)
# Язык плагина
language: 'en'

# Enable autologin? (using IP and Client ID)
# Включить автоматический вход? (используя IP и Client ID)
enable_autologin: false

# Time format (e.g in /myadmin info)
# Формат времени (например в /myadmin info)
time_format: 'd.m.Y H:i:s'
...